### ISSUE TITLE
Question: Docker restarting

### ISSUE THREAD

**Issue by Idriel** [dragoangel/parsedmarc-dockerized#1]
Hi, 
I just took parsedmarc Dokcerfile and modifed command
CMD ["parsedmarc", "-c", "/etc/parsedmarc.ini"]

When Docker start, i'll read config file, i'll do the job (read email, parse report, send into ELK or Splunk) but Docker goes to restart. 
Do you have this challanges? 
How can we create this more demonized so I dont have docker restart all the time but just watch for email or i'll run it over scheduled task?

**Comment by dragoangel** [comment]
Need to check this, do you have errors in docker? This maybe the case.

**Comment by dragoangel** [comment]
In my environment it works without restart:
`parsedmarc      parsedmarc -c /etc/parsedm ...   Up`
So I assume you have changed your command incorrectly (like not escape white spaces, etc) which generate error and lead to restart of container.
