### ISSUE TITLE
Disable exposing kibana per default

### ISSUE THREAD

**Issue by Zocker1999NET** [dragoangel/parsedmarc-dockerized#12]
https://github.com/dragoangel/parsedmarc-dockerized/blob/753fe36d9bb385f49365728112b74a4663085e08/docker-compose.yml#L53-L54

You should be able to remove these lines because nginx is able to access kibana using the Docker internal network. If this line stays and users let them there, kibana is also published (and may be worldwide accessable as Docker sometimes circumvents software firewalls due to their usage of iptables for redirection).

**Comment by dragoangel** [comment]
Resolved as #14
