### ISSUE TITLE
GeoLite2-Country.mmdb is missing

### ISSUE THREAD

**Issue by zajinx** [dragoangel/parsedmarc-dockerized#2]
I used the latest version from the repo and i get the error from below in my parsedmarc container, are you planing to push a fix?

WARNING:utils.py:296:GeoLite2-Country.mmdb is missing. Please follow the instructions at https://dev.maxmind.com/geoip/geoipupdate/ to get the latest version

**Comment by eekdood** [comment]
I've resorted to a temporary workaround of installing and configuring geoipupdate on the docker host and mounting the database folder as a volume on the parsedmarc container.

**Comment by dragoangel** [comment]
Hi @zajinx currently maxmind require api key to download geoip and their license not allow to share this file, I need update readme.md, forget about it.

**Comment by dragoangel** [comment]
@eekdood could you please create a PR?

**Comment by eekdood** [comment]
@zajinx my PR was merged. Have a look at the updated `README` for guidance on resolving your error.

**Comment by dragoangel** [comment]
@eekdood thanks for PR
