### ISSUE TITLE
Link false in how-to-from-scratch

### ISSUE THREAD

**Issue by schoebelh** [dragoangel/parsedmarc-dockerized#4]
At Number 10 - Kibana import... Will be this correct: https://raw.githubusercontent.com/domainaware/parsedmarc/master/kibana/export.ndjson...?

If i try to import these file kibana will not come to success :-/

**Comment by schoebelh** [comment]
After adjusting the image versions of elasticsearch and kibana in docker-compose.yml to 7.8.1 i was able to import the export.ndjson without errors.

**Comment by dragoangel** [comment]
Hi @schoebelh I'm not updated for a while. Will try to check this on week when have time. Thanks for your report ☺️
