### ISSUE TITLE
kibana_saved_objects.json

### ISSUE THREAD

**Issue by JeremyHutchings** [dragoangel/parsedmarc-dockerized#5]
Do you know of the new location of kibana_saved_objects.json  ?

**Comment by pkntl** [comment]
They don't appear to use .json files any more. The file I found is an .ndjson file here: https://raw.githubusercontent.com/domainaware/parsedmarc/master/kibana/export.ndjson

I had to change the version of elasticsearch and kibana in the docker-compose.yml file to versions 7.9.3.

Everything seems to work now. Hope this helps.

**Comment by andreas5232** [comment]
I just stumbled upon the same issue, but after changing the elasticsearch and kibana version to 7.9.3 and using the .ndjson file @desigi mentioned, ist is perfectly running now. Thanks for this quick fix!
