### ISSUE TITLE
Docker Composer Install Command Issue

### ISSUE THREAD

**Issue by justgosh** [dragoangel/parsedmarc-dockerized#9]
curl -L https://github.com/docker/compose/releases/download/1.24.1/docker-compose-Linux-x86_64 > /usr/local/bin/docker-compose
returns
Warning: Binary output can mess up your terminal. Use "--output -" to tell
Warning: curl to output it to your terminal anyway, or consider "--output
Warning: <FILE>" to save to a file.

sudo curl -L "https://github.com/docker/compose/releases/download/v2.3.4/docker-compose-linux-x86_64" -o /usr/local/bin/docker-compose
Works

**Comment by dragoangel** [comment]
fixed with 753fe36d9bb385f49365728112b74a4663085e08
